# goodsync/Dockerfile
FROM debian:jessie-slim
MAINTAINER And Grin <grin@grin.ly>

# s6 overlay
ADD https://github.com/just-containers/s6-overlay/releases/download/v1.20.0.0/s6-overlay-amd64.tar.gz /tmp/s6-overlay.tar.gz
RUN tar xvzf /tmp/s6-overlay.tar.gz -C / && \
		rm /tmp/s6-overlay.tar.gz

WORKDIR /gs
ADD http://www.goodsync.com/download/goodsync-release-x86_64.tar.gz /gs/goodsync-release-x86_64.tar.gz
RUN tar xvzf goodsync-release-x86_64.tar.gz --strip-components=1 && \
		rm /gs/goodsync-release-x86_64.tar.gz && \
		./gs-server /set-admin=${GOODSYNC_USER}:${GOODSYNC_PWD}

# root filesystem
#COPY rootfs /
COPY ./settings.tix /root/.goodsync/server/settings.tix

EXPOSE 33333

# INIT
ENTRYPOINT [ "/init" ]

# Run GS
CMD ["./gs-server"]
